import React,{useEffect,useMemo,useState} from 'react';
import {collection,deleteDoc,doc,getDocs,setDoc} from 'firebase/firestore';
import {auth,db} from './firebase';
import {printRecords,toggleSelection,selectAll} from './recordTools';
const green='#31533a',bright='#3dad2d',border='#dfe5dc';const input={width:'100%',boxSizing:'border-box',padding:'9px 11px',border:`1px solid ${border}`,borderRadius:8};
const b=(kind='primary')=>({border:0,background:kind==='primary'?bright:kind==='danger'?'#b93333':'#e9eee7',color:kind==='primary'||kind==='danger'?'#fff':green,padding:'8px 11px',borderRadius:8,fontWeight:800,cursor:'pointer'});
const empty={idParticipante:'',paciente:'',fecha:'',tipo:'Consulta',diagnostico:'',tratamiento:'',proximaCita:'',reporte:'',facturaUrl:'',honorarios:'',estatus:'Atendido'};
const cols=[{label:'ID participante',key:'idParticipante'},{label:'Paciente',key:'paciente'},{label:'Fecha',key:'fecha'},{label:'Tipo',key:'tipo'},{label:'Diagnóstico',key:'diagnostico'},{label:'Tratamiento',key:'tratamiento'},{label:'Próxima cita',key:'proximaCita'},{label:'Honorarios',key:'honorarios'},{label:'Estatus',key:'estatus'}];
export default function DentalModule(){
 const [rows,setRows]=useState([]),[f,setF]=useState(empty),[msg,setMsg]=useState(''),[editing,setEditing]=useState(null),[selected,setSelected]=useState(new Set());
 async function load(){const s=await getDocs(collection(db,'consultorioDental'));setRows(s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(b.fecha||'').localeCompare(String(a.fecha||''))));}
 useEffect(()=>{load().catch(()=>{});},[]);
 const selectedRows=useMemo(()=>rows.filter(x=>selected.has(x.id)),[rows,selected]);
 async function save(){if(!f.paciente.trim()){setMsg('Paciente es obligatorio.');return;}const id=editing||`${Date.now()}-${Math.random().toString(36).slice(2,6)}`;await setDoc(doc(db,'consultorioDental',id),{...f,actualizadoEn:new Date().toISOString(),capturadoPor:auth.currentUser?.email||''},{merge:false});setF(empty);setEditing(null);setMsg(editing?'Registro actualizado.':'Registro clínico guardado.');load();}
 function edit(x){setEditing(x.id);setF({...empty,...x});window.scrollTo({top:0,behavior:'smooth'});}
 async function remove(x){if(!confirm(`¿Borrar el registro de ${x.paciente}?`))return;await deleteDoc(doc(db,'consultorioDental',x.id));setSelected(s=>{const n=new Set(s);n.delete(x.id);return n});load();}
 async function removeSelected(){if(!selectedRows.length||!confirm(`¿Borrar ${selectedRows.length} registro(s) seleccionados?`))return;for(const x of selectedRows)await deleteDoc(doc(db,'consultorioDental',x.id));setSelected(new Set());load();}
 return <div><div style={{background:'#fff',border:`1px solid ${border}`,borderRadius:12,padding:16}}><h2 style={{color:green,marginTop:0}}>{editing?'Editar registro dental':'Consultorio Dental'}</h2><p style={{fontSize:13}}>Expedientes clínicos, citas, reportes y facturación del prestador.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:9}}><input style={input} placeholder="ID participante" value={f.idParticipante} onChange={e=>setF({...f,idParticipante:e.target.value})}/><input style={input} placeholder="Paciente" value={f.paciente} onChange={e=>setF({...f,paciente:e.target.value})}/><input style={input} type="date" value={f.fecha} onChange={e=>setF({...f,fecha:e.target.value})}/><select style={input} value={f.tipo} onChange={e=>setF({...f,tipo:e.target.value})}><option>Consulta</option><option>Limpieza</option><option>Extracción</option><option>Restauración</option><option>Urgencia</option><option>Otro</option></select><input style={input} placeholder="Próxima cita" type="datetime-local" value={f.proximaCita} onChange={e=>setF({...f,proximaCita:e.target.value})}/><input style={input} placeholder="Honorarios" type="number" value={f.honorarios} onChange={e=>setF({...f,honorarios:e.target.value})}/><input style={input} placeholder="URL factura / comprobante" value={f.facturaUrl} onChange={e=>setF({...f,facturaUrl:e.target.value})}/></div><textarea style={{...input,minHeight:60,marginTop:9}} placeholder="Diagnóstico" value={f.diagnostico} onChange={e=>setF({...f,diagnostico:e.target.value})}/><textarea style={{...input,minHeight:60,marginTop:9}} placeholder="Tratamiento" value={f.tratamiento} onChange={e=>setF({...f,tratamiento:e.target.value})}/><textarea style={{...input,minHeight:60,marginTop:9}} placeholder="Reporte / observaciones" value={f.reporte} onChange={e=>setF({...f,reporte:e.target.value})}/><div style={{display:'flex',gap:8,marginTop:9}}><button style={b()} onClick={save}>{editing?'Actualizar registro':'Guardar en expediente'}</button>{editing&&<button style={b('secondary')} onClick={()=>{setEditing(null);setF(empty)}}>Cancelar</button>}</div>{msg&&<span style={{display:'block',marginTop:8,color:green}}>{msg}</span>}</div>
 <div style={{display:'flex',gap:8,margin:'12px 0',flexWrap:'wrap'}}><button style={b('secondary')} onClick={()=>setSelected(selected.size===rows.length?new Set():selectAll(rows.map(x=>x.id)))}>{selected.size===rows.length&&rows.length?'Quitar selección':'Seleccionar todos'}</button><button style={b('secondary')} disabled={!selectedRows.length} onClick={()=>printRecords('Consultorio dental',selectedRows,cols)}>Imprimir seleccionados ({selectedRows.length})</button><button style={b('danger')} disabled={!selectedRows.length} onClick={removeSelected}>Borrar seleccionados</button></div>
 <div style={{display:'grid',gap:8}}>{rows.map(x=><div key={x.id} style={{background:'#fff',border:`1px solid ${border}`,borderRadius:10,padding:12,display:'grid',gridTemplateColumns:'28px 1fr auto',gap:10,alignItems:'start'}}><input type="checkbox" checked={selected.has(x.id)} onChange={()=>setSelected(s=>toggleSelection(s,x.id))}/><div><b>{x.paciente}</b> · {x.fecha} · {x.tipo}<div style={{fontSize:12,marginTop:4}}>{x.diagnostico} {x.tratamiento&&`· ${x.tratamiento}`}</div>{x.proximaCita&&<div style={{fontSize:12}}>Próxima cita: {x.proximaCita}</div>}{x.facturaUrl&&<a href={x.facturaUrl} target="_blank" rel="noreferrer">Factura</a>}</div><div style={{display:'flex',gap:6,flexWrap:'wrap'}}><button style={b('secondary')} onClick={()=>edit(x)}>Editar</button><button style={b('secondary')} onClick={()=>printRecords(`Registro dental · ${x.paciente}`,[x],cols)}>Imprimir</button><button style={b('danger')} onClick={()=>remove(x)}>Borrar</button></div></div>)}</div></div>
}
