import React,{useEffect,useMemo,useState} from 'react';
import {collection,deleteDoc,doc,getDocs,updateDoc} from 'firebase/firestore';
import {db} from './firebase';
import {printRecords,toggleSelection,selectAll} from './recordTools';
const green='#31533a',bright='#3dad2d',border='#dfe5dc',muted='#667268',danger='#b93333';
const card={background:'#fff',border:`1px solid ${border}`,borderRadius:12,padding:14};
const input={width:'100%',boxSizing:'border-box',padding:'9px 11px',border:`1px solid ${border}`,borderRadius:8,background:'#fff'};
const btn=(p=false)=>({border:0,borderRadius:8,padding:'8px 11px',fontWeight:800,cursor:'pointer',background:p?bright:'#e8eee6',color:p?'#fff':green});
const norm=v=>String(v??'').trim().toLocaleLowerCase('es-MX').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\p{L}\p{N}]+/gu,' ').replace(/\s+/g,' ').trim();
const nk=v=>norm(v).replace(/\s/g,'');
const money=v=>{if(typeof v==='number')return v;const n=Number(String(v??'').replace(/[$,\s]/g,''));return Number.isFinite(n)?n:0};
const answerEntries=sol=>Object.values(sol?.respuestas||{}).map(v=>({label:String(v?.etiqueta||''),value:v?.valor??v?.archivoNombre??''}));
const answer=(sol,keys)=>{for(const x of answerEntries(sol)){const l=norm(x.label);if(keys.some(k=>l===norm(k)||l.includes(norm(k))))return String(x.value||'').trim()}return ''};
const worker=sol=>answer(sol,['nombre del colaborador','nombre del trabajador','nombre del empleado','colaborador','trabajador','empleado'])||sol.trabajadorNombre||sol.colaboradorNombre||'';
const participantMatch=(p,row)=>!!p&&!!row&&((p.docId&&row.participanteDocId===p.docId)||(p.docId&&row.docId===p.docId)||(p.idParticipante&&row.idParticipante&&nk(p.idParticipante)===nk(row.idParticipante))||(p.nombre&&row.nombre&&norm(p.nombre)===norm(row.nombre)));
const amountFromObject=o=>{let total=0;for(const [k,v] of Object.entries(o||{})){const l=norm(k);if(/monto|importe|valor.*beneficio|inversion|inversión|costo.*apoyo/.test(l))total+=money(v)}return total};
const amountFromRequest=s=>answerEntries(s).reduce((sum,x)=>/monto|importe|valor del beneficio|inversion|inversión|costo del apoyo/.test(norm(x.label))?sum+money(x.value):sum,0);
const relatedNames=s=>answerEntries(s).filter(x=>/becado|beneficiario|hijo|hija|tutelad|dependiente|conyuge|cónyuge|paciente/.test(norm(x.label))&&!/trabajador|colaborador|empleado/.test(norm(x.label))).map(x=>({tipo:x.label,nombre:String(x.value||'').trim()})).filter(x=>x.nombre);

export default function ExpedientesParticipantes(){
 const [p,setP]=useState([]),[programas,setProgramas]=useState([]),[acts,setActs]=useState([]),[sols,setSols]=useState([]),[dental,setDental]=useState([]),[q,setQ]=useState(''),[sel,setSel]=useState(null),[loading,setLoading]=useState(true);
 const [selected,setSelected]=useState(new Set()),[editing,setEditing]=useState(null),[editForm,setEditForm]=useState({}),[bulkOpen,setBulkOpen]=useState(false),[bulk,setBulk]=useState({sucursal:'',estatus:'',expedienteEstado:''}),[msg,setMsg]=useState('');
 async function load(){setLoading(true);const names=['participantesPrima','programas','actividades','solicitudes','consultorioDental'];const out={};for(const n of names){try{const snap=await getDocs(collection(db,n));out[n]=snap.docs.map(d=>({id:d.id,docId:d.id,...d.data()}))}catch{out[n]=[]}}setP(out.participantesPrima.sort((a,b)=>String(a.nombre||'').localeCompare(String(b.nombre||''),'es')));setProgramas(out.programas);setActs(out.actividades);setSols(out.solicitudes);setDental(out.consultorioDental);setLoading(false)}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>{const n=norm(q);return p.filter(x=>!n||norm(`${x.idParticipante||''} ${x.nombre||''} ${x.sucursal||''}`).includes(n))},[p,q]);
 function build(pers){
  const solicitudes=sols.filter(s=>(s.participanteDocId&&s.participanteDocId===pers.docId)||(s.idParticipante&&pers.idParticipante&&nk(s.idParticipante)===nk(pers.idParticipante))||(worker(s)&&norm(worker(s))===norm(pers.nombre)));
  const actividades=acts.filter(a=>(a.participantes||[]).some(r=>participantMatch(pers,r))||solicitudes.some(s=>s.actividadId===a.id));
  const dentalRows=dental.filter(d=>(d.idParticipante&&pers.idParticipante&&nk(d.idParticipante)===nk(pers.idParticipante))||(d.paciente&&norm(d.paciente)===norm(pers.nombre)));
  const beneficios=[];
  for(const a of actividades){const prog=programas.find(x=>x.id===a.programaId);const row=(a.participantes||[]).find(r=>participantMatch(pers,r));beneficios.push({programa:prog?.nombre||'Programa / servicio',actividad:a.nombre||'Actividad',tipo:'Participación',beneficiario:pers.nombre,monto:amountFromObject(row?.datos||row||{}),origen:'Actividad'});}
  for(const s of solicitudes.filter(x=>x.estatus==='Aprobado')){const prog=programas.find(x=>x.id===s.programaId),act=acts.find(x=>x.id===s.actividadId),rels=relatedNames(s),m=amountFromRequest(s)||money(s.monto)||money(s.valorBeneficio);if(rels.length){rels.forEach(r=>beneficios.push({programa:prog?.nombre||s.programaNombre||'Programa',actividad:act?.nombre||s.formularioNombre||'Solicitud aprobada',tipo:r.tipo,beneficiario:r.nombre,monto:m/rels.length,origen:'Solicitud'}))}else beneficios.push({programa:prog?.nombre||s.programaNombre||'Programa',actividad:act?.nombre||s.formularioNombre||'Solicitud aprobada',tipo:'Beneficio directo',beneficiario:pers.nombre,monto:m,origen:'Solicitud'});}
  for(const d of dentalRows)beneficios.push({programa:'Consultorio Dental',actividad:d.tipo||d.tratamiento||'Atención dental',tipo:'Atención médica/dental',beneficiario:d.paciente||pers.nombre,monto:money(d.honorarios)||money(d.costo)||0,origen:'Consultorio dental'});
  const uniq=[],keys=new Set();for(const b of beneficios){const k=[norm(b.programa),norm(b.actividad),norm(b.beneficiario),b.monto,b.origen].join('|');if(!keys.has(k)){keys.add(k);uniq.push(b)}}
  const beneficiaries=[...new Map(uniq.filter(b=>b.beneficiario&&norm(b.beneficiario)!==norm(pers.nombre)).map(b=>[norm(b.beneficiario),{nombre:b.beneficiario,relacion:b.tipo,programas:new Set([b.programa])}])).values()];
  return {solicitudes,actividades,dentalRows,beneficios:uniq,beneficiaries,total:uniq.reduce((s,b)=>s+money(b.monto),0)};
 }
 const selectedRows=useMemo(()=>p.filter(x=>selected.has(x.docId)),[p,selected]);
 const data=sel?build(sel):null;
 const fichaCols=[{label:'ID',key:'idParticipante'},{label:'Colaborador / trabajador',key:'nombre'},{label:'Sucursal',key:'sucursal'},{label:'Teléfono',value:x=>x.telefono||x.celular||''},{label:'Correo',value:x=>x.correo||x.email||''},{label:'Temporada',key:'temporada'},{label:'Estatus',key:'estatus'},{label:'Expediente',key:'expedienteEstado'}];
 const printCols=[{label:'Programa',key:'programa'},{label:'Actividad / apoyo',key:'actividad'},{label:'Beneficiario',key:'beneficiario'},{label:'Tipo',key:'tipo'},{label:'Valor / inversión',value:x=>`$${money(x.monto).toLocaleString('es-MX',{minimumFractionDigits:2})}`}];
 function startEdit(x){setEditing(x.docId);setEditForm({...x});setMsg('')}
 async function saveEdit(){if(!editing)return;const id=editing;const payload={nombre:String(editForm.nombre||'').trim(),sucursal:editForm.sucursal||'',telefono:editForm.telefono||editForm.celular||'',correo:editForm.correo||editForm.email||'',temporada:editForm.temporada||'',estatus:editForm.estatus||'Vigente',expedienteEstado:editForm.expedienteEstado||'Incompleto',expedienteUrl:editForm.expedienteUrl||'',observaciones:editForm.observaciones||'',actualizadoEn:new Date().toISOString()};await updateDoc(doc(db,'participantesPrima',id),payload);setEditing(null);setEditForm({});setMsg('Expediente actualizado.');if(sel?.docId===id)setSel({...sel,...payload});await load()}
 async function removeOne(x){if(!confirm(`¿Eliminar a ${x.nombre} del padrón? Se conserva el historial de solicitudes, actividades y servicios, pero dejará de aparecer como participante activo.`))return;await deleteDoc(doc(db,'participantesPrima',x.docId));setSelected(v=>{const n=new Set(v);n.delete(x.docId);return n});if(sel?.docId===x.docId)setSel(null);setMsg('Registro eliminado del padrón.');await load()}
 async function removeSelected(){if(!selectedRows.length||!confirm(`¿Eliminar ${selectedRows.length} registro(s) seleccionados del padrón?`))return;for(const x of selectedRows)await deleteDoc(doc(db,'participantesPrima',x.docId));setSelected(new Set());setMsg(`${selectedRows.length} registro(s) eliminados.`);await load()}
 async function bulkEdit(){const changes={};for(const k of ['sucursal','estatus','expedienteEstado'])if(bulk[k])changes[k]=bulk[k];if(!Object.keys(changes).length){setMsg('Selecciona al menos un dato para modificar.');return}changes.actualizadoEn=new Date().toISOString();for(const x of selectedRows)await updateDoc(doc(db,'participantesPrima',x.docId),changes);setBulkOpen(false);setBulk({sucursal:'',estatus:'',expedienteEstado:''});setMsg(`${selectedRows.length} expediente(s) actualizados.`);await load()}
 function printFull(x){const d=build(x);printRecords(`Expediente integral · ${x.nombre}`,[{...x,total:d.total,actividades:d.actividades.length,solicitudes:d.solicitudes.length,beneficiarios:d.beneficiaries.length}],[...fichaCols,{label:'Actividades',key:'actividades'},{label:'Solicitudes',key:'solicitudes'},{label:'Beneficiarios relacionados',key:'beneficiarios'},{label:'Inversión / valor acumulado',value:r=>`$${money(r.total).toLocaleString('es-MX',{minimumFractionDigits:2})}`}])}
 if(loading)return <div>Cargando expedientes…</div>;
 if(sel&&data)return <div>
  <div style={{display:'flex',justifyContent:'space-between',gap:8,flexWrap:'wrap',marginBottom:10}}><div><button style={btn()} onClick={()=>setSel(null)}>← Expedientes</button><h2 style={{color:green,margin:'8px 0 0'}}>{sel.nombre}</h2><div style={{fontSize:12,color:muted}}>Expediente integral · {sel.idParticipante||'ID pendiente'}</div></div><div style={{display:'flex',gap:6,flexWrap:'wrap'}}><button style={btn()} onClick={()=>startEdit(sel)}>Editar</button><button style={btn(true)} onClick={()=>printFull(sel)}>Imprimir expediente</button><button style={btn()} onClick={()=>printRecords(`Historial de beneficios · ${sel.nombre}`,data.beneficios,printCols)}>Imprimir beneficios</button><button style={{...btn(),background:danger,color:'#fff'}} onClick={()=>removeOne(sel)}>Eliminar</button></div></div>
  {editing===sel.docId&&<div style={{...card,marginBottom:9,background:'#f8faf6'}}><b style={{color:green}}>Editar expediente del participante</b><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:7,marginTop:8}}><input style={input} value={editForm.nombre||''} placeholder="Colaborador / trabajador" onChange={e=>setEditForm({...editForm,nombre:e.target.value})}/><select style={input} value={editForm.sucursal||''} onChange={e=>setEditForm({...editForm,sucursal:e.target.value})}><option value="">Sucursal pendiente</option><option>Bácum</option><option>Caborca</option></select><input style={input} value={editForm.area||''} placeholder="Área" onChange={e=>setEditForm({...editForm,area:e.target.value})}/><input style={input} value={editForm.telefono||editForm.celular||''} placeholder="Teléfono" onChange={e=>setEditForm({...editForm,telefono:e.target.value})}/><input style={input} value={editForm.correo||editForm.email||''} placeholder="Correo" onChange={e=>setEditForm({...editForm,correo:e.target.value})}/><input style={input} value={editForm.temporada||''} placeholder="Temporada" onChange={e=>setEditForm({...editForm,temporada:e.target.value})}/><select style={input} value={editForm.estatus||'Vigente'} onChange={e=>setEditForm({...editForm,estatus:e.target.value})}><option>Vigente</option><option>No elegible</option><option>Revisión especial</option><option>Histórico</option></select><select style={input} value={editForm.expedienteEstado||'Incompleto'} onChange={e=>setEditForm({...editForm,expedienteEstado:e.target.value})}><option>Completo</option><option>Incompleto</option><option>En revisión</option><option>Sin expediente</option></select></div><div style={{display:'flex',gap:6,marginTop:8}}><button style={btn(true)} onClick={saveEdit}>Guardar cambios</button><button style={btn()} onClick={()=>{setEditing(null);setEditForm({})}}>Cancelar</button></div></div>}
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:9,marginBottom:9}}><div style={card}><b>Ficha de contacto y registro</b><div style={{fontSize:12,lineHeight:1.7,marginTop:6}}>ID: {sel.idParticipante||'Pendiente'}<br/>Sucursal: {sel.sucursal||'—'}<br/>Teléfono: {sel.telefono||sel.celular||'—'}<br/>Correo: {sel.correo||sel.email||'—'}<br/>Temporada: {sel.temporada||'—'}<br/>Estatus: {sel.estatus||'Vigente'}<br/>Expediente: {sel.expedienteEstado||'Incompleto'}</div></div><div style={card}><b>Resumen social</b><div style={{fontSize:27,fontWeight:900,color:green,marginTop:7}}>${data.total.toLocaleString('es-MX',{minimumFractionDigits:2})}</div><div style={{fontSize:12,color:muted}}>Inversión/valor identificado a favor del participante y sus beneficiarios</div><div style={{marginTop:7,fontSize:12}}>{data.actividades.length} actividades · {data.solicitudes.length} solicitudes · {data.beneficiaries.length} beneficiarios relacionados</div></div></div>
  <div style={{...card,marginBottom:9}}><b>Beneficiarios directos e indirectos relacionados</b>{data.beneficiaries.length?<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:7,marginTop:7}}>{data.beneficiaries.map((b,i)=><div key={i} style={{padding:9,background:'#f5f7f2',borderRadius:8}}><b>{b.nombre}</b><div style={{fontSize:11,color:muted}}>{b.relacion}</div></div>)}</div>:<div style={{fontSize:12,color:muted,marginTop:6}}>No se han identificado beneficiarios relacionados en los registros disponibles.</div>}</div>
  <div style={card}><b>Programas, servicios y beneficios recibidos</b><div style={{overflowX:'auto',marginTop:7}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:12,minWidth:760}}><thead><tr>{['Programa / servicio','Actividad / apoyo','Beneficiario','Tipo','Inversión / valor'].map(h=><th key={h} style={{textAlign:'left',padding:8,borderBottom:`1px solid ${border}`,color:green}}>{h}</th>)}</tr></thead><tbody>{data.beneficios.map((b,i)=><tr key={i}><td style={{padding:8,borderBottom:`1px solid ${border}`}}><b>{b.programa}</b></td><td style={{padding:8,borderBottom:`1px solid ${border}`}}>{b.actividad}</td><td style={{padding:8,borderBottom:`1px solid ${border}`}}>{b.beneficiario}</td><td style={{padding:8,borderBottom:`1px solid ${border}`}}>{b.tipo}</td><td style={{padding:8,borderBottom:`1px solid ${border}`}}>${money(b.monto).toLocaleString('es-MX',{minimumFractionDigits:2})}</td></tr>)}{!data.beneficios.length&&<tr><td colSpan="5" style={{padding:14,color:muted}}>Todavía no hay beneficios vinculados.</td></tr>}</tbody></table></div></div>
 </div>;
 return <div>
  <div style={{display:'flex',justifyContent:'space-between',gap:9,alignItems:'center',flexWrap:'wrap',marginBottom:10}}><div><h2 style={{margin:0,color:green}}>Expedientes de participantes</h2><div style={{fontSize:12,color:muted}}>Salida del cajón: expediente consolidado de cada colaborador, su participación, beneficiarios e inversión acumulada.</div></div><input style={{...input,maxWidth:380}} placeholder="Buscar por ID, colaborador, sucursal o área" value={q} onChange={e=>setQ(e.target.value)}/></div>
  {msg&&<div style={{...card,marginBottom:9,padding:9,color:green,fontSize:12,fontWeight:800}}>{msg}</div>}
  <div style={{...card,marginBottom:10}}><div style={{display:'flex',gap:6,flexWrap:'wrap',alignItems:'center'}}><button style={btn()} onClick={()=>setSelected(selected.size===filtered.length&&filtered.length?new Set():selectAll(filtered.map(x=>x.docId)))}>{selected.size===filtered.length&&filtered.length?'Quitar selección':'Seleccionar visibles'}</button><span style={{fontSize:12,color:muted}}>{selectedRows.length} seleccionados</span><button style={btn()} disabled={!selectedRows.length} onClick={()=>setBulkOpen(v=>!v)}>Editar seleccionados</button><button style={btn()} disabled={!selectedRows.length} onClick={()=>printRecords('Expedientes seleccionados',selectedRows.map(x=>{const d=build(x);return {...x,total:d.total}}),[...fichaCols,{label:'Inversión / valor',value:r=>`$${money(r.total).toLocaleString('es-MX',{minimumFractionDigits:2})}`}])}>Imprimir seleccionados</button><button style={{...btn(),background:danger,color:'#fff'}} disabled={!selectedRows.length} onClick={removeSelected}>Eliminar seleccionados</button></div>{bulkOpen&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:7,marginTop:8}}><select style={input} value={bulk.sucursal} onChange={e=>setBulk({...bulk,sucursal:e.target.value})}><option value="">Sucursal: sin cambio</option><option>Bácum</option><option>Caborca</option></select><input style={input} placeholder="Área: sin cambio" value={bulk.area} onChange={e=>setBulk({...bulk,area:e.target.value})}/><select style={input} value={bulk.estatus} onChange={e=>setBulk({...bulk,estatus:e.target.value})}><option value="">Estatus: sin cambio</option><option>Vigente</option><option>No elegible</option><option>Revisión especial</option><option>Histórico</option></select><select style={input} value={bulk.expedienteEstado} onChange={e=>setBulk({...bulk,expedienteEstado:e.target.value})}><option value="">Expediente: sin cambio</option><option>Completo</option><option>Incompleto</option><option>En revisión</option><option>Sin expediente</option></select><button style={btn(true)} onClick={bulkEdit}>Aplicar edición masiva</button></div>}</div>
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:9}}>{filtered.map(x=>{const d=build(x);return <div key={x.docId} style={card}><div style={{display:'flex',justifyContent:'space-between',gap:8,alignItems:'start'}}><div style={{display:'flex',gap:7,alignItems:'start'}}><input type="checkbox" checked={selected.has(x.docId)} onChange={()=>setSelected(v=>toggleSelection(v,x.docId))}/><div><button type="button" onClick={()=>setSel(x)} style={{border:0,background:'none',padding:0,color:green,fontWeight:900,fontSize:15,cursor:'pointer',textAlign:'left'}}>{x.nombre}</button><div style={{fontSize:11,color:muted}}>{x.idParticipante||'ID pendiente'} · {x.sucursal||'Sin sucursal'}</div></div></div><div style={{fontSize:17,fontWeight:900,color:green}}>${d.total.toLocaleString('es-MX',{maximumFractionDigits:0})}</div></div><div style={{fontSize:11,color:muted,marginTop:8}}>{d.actividades.length} actividades · {d.beneficiaries.length} beneficiarios relacionados</div><div style={{display:'flex',gap:5,flexWrap:'wrap',marginTop:9}}><button style={btn()} onClick={()=>setSel(x)}>Ver</button><button style={btn()} onClick={()=>{setSel(x);startEdit(x)}}>Editar</button><button style={btn()} onClick={()=>printFull(x)}>Imprimir</button><button style={{...btn(),background:danger,color:'#fff'}} onClick={()=>removeOne(x)}>Eliminar</button></div></div>})}{!filtered.length&&<div style={card}>No hay expedientes que coincidan con la búsqueda.</div>}</div>
 </div>;
}
