import React,{useEffect,useState} from 'react';
import {doc,getDoc} from 'firebase/firestore';
import {db} from './firebase';
const green='#31533a',bg='#f5f7f2',border='#dfe5dc',muted='#667268';
const maskEmail=(v='')=>{const [a,b]=String(v).split('@');return a&&b?`${a.slice(0,2)}***@${b}`:'—'};
export default function FirmaVerificacion({id}){
 const [data,setData]=useState(undefined);
 useEffect(()=>{(async()=>{try{const s=await getDoc(doc(db,'actaFirmas',id));setData(s.exists()?{id:s.id,...s.data()}:null)}catch(e){console.error(e);setData(null)}})()},[id]);
 if(data===undefined)return <div style={{fontFamily:'Arial',padding:30}}>Verificando firma…</div>;
 return <main style={{fontFamily:'Arial,sans-serif',background:bg,minHeight:'100vh',padding:'26px 14px',color:'#263329'}}><div style={{maxWidth:760,margin:'0 auto',background:'#fff',border:`1px solid ${border}`,borderRadius:14,padding:24}}><div style={{textAlign:'center'}}><img src="/logo-asociacion-comercio-justo.png" alt="" style={{maxWidth:150,maxHeight:100}}/><h2 style={{color:green,marginBottom:3}}>Verificación de Firma NODO</h2><div style={{fontSize:12,color:muted}}>Asociación de Comercio Justo Campos Bórquez A.C.</div></div>{!data?<div style={{marginTop:22,padding:14,background:'#fff0f0',borderRadius:9}}>No se encontró el registro de firma.</div>:data.estado!=='Firmado'||!data.firmaNodo?<div style={{marginTop:22,padding:14,background:'#fff5d9',borderRadius:9}}>Este registro existe, pero todavía no contiene una Firma NODO finalizada.</div>:<div style={{marginTop:22}}><div style={{padding:14,background:'#edf7ea',borderRadius:9,color:green,fontWeight:800}}>Firma registrada y localizada en NODO.</div><table style={{width:'100%',borderCollapse:'collapse',fontSize:12,marginTop:14}}><tbody>{[['Documento',`${data.tipoDocumento||'Acta'} · ${data.titulo||''}`],['Firmante',data.nombre||''],['Cuenta verificada',maskEmail(data.firmaNodo.email||data.correo||'')],['Fecha/hora de firma',data.firmaNodo.signedAt?new Date(data.firmaNodo.signedAt).toLocaleString('es-MX'):''],['Versión del documento',String(data.versionDocumento||1)],['Cadena de firma',data.firmaNodo.signatureCode||''],['Hash SHA-256',data.firmaNodo.documentHash||'']].map(([k,v])=><tr key={k}><td style={{border:`1px solid ${border}`,padding:8,fontWeight:800,width:'30%'}}>{k}</td><td style={{border:`1px solid ${border}`,padding:8,wordBreak:'break-all'}}>{v}</td></tr>)}</tbody></table><p style={{fontSize:10,color:muted,marginTop:16}}>Esta consulta confirma la existencia del registro criptográfico de Firma NODO. Firma NODO es una firma electrónica institucional; no se presenta como e.firma/FIEL ni como Firma Electrónica Avanzada.</p></div>}</div></main>
}
