import React,{useEffect,useState} from 'react';
import {doc,getDoc,setDoc} from 'firebase/firestore';
import {db} from './firebase';
const green='#31533a',border='#dfe5dc',muted='#667268';
export default function FirmaActaPublica({token}){
 const [data,setData]=useState(null),[busy,setBusy]=useState(true),[checked,setChecked]=useState(false),[msg,setMsg]=useState('');
 useEffect(()=>{(async()=>{try{const s=await getDoc(doc(db,'actaFirmas',token));setData(s.exists()?{id:s.id,...s.data()}:null);}catch(e){console.error(e);setData(null)}finally{setBusy(false)}})()},[token]);
 async function aceptar(){if(!checked||!data||data.estado==='Conforme')return;const at=new Date().toISOString();try{await setDoc(doc(db,'actaFirmas',token),{estado:'Conforme',conformidadEn:at,metodo:'Conformidad electrónica',declaracionAceptada:true},{merge:true});setData({...data,estado:'Conforme',conformidadEn:at,metodo:'Conformidad electrónica',declaracionAceptada:true});setMsg('Tu conformidad quedó registrada correctamente.');}catch(e){console.error(e);setMsg('No fue posible registrar la conformidad.');}}
 if(busy)return <div style={{fontFamily:'Arial,sans-serif',padding:30}}>Cargando documento…</div>;
 if(!data)return <div style={{fontFamily:'Arial,sans-serif',maxWidth:720,margin:'50px auto',padding:24}}>El enlace no es válido o ya no está disponible.</div>;
 return <main style={{fontFamily:'Arial,sans-serif',background:'#f5f7f2',minHeight:'100vh',padding:'24px 14px',color:'#222'}}><div style={{maxWidth:760,margin:'0 auto',background:'#fff',border:`1px solid ${border}`,borderRadius:14,padding:24}}><div style={{textAlign:'center'}}><img src="/logo-asociacion-comercio-justo.png" alt="" style={{maxWidth:150,maxHeight:100}}/><h2 style={{color:green,marginBottom:3}}>Conformidad de acta / minuta</h2><div style={{fontSize:12,color:muted}}>Asociación de Comercio Justo Campos Bórquez A.C.</div></div><hr style={{border:0,borderTop:`1px solid ${border}`,margin:'18px 0'}}/><h3 style={{color:green}}>{data.tipoDocumento}: {data.titulo}</h3><div style={{fontSize:13,lineHeight:1.55}}><b>Participante:</b> {data.nombre}<br/><b>Fecha:</b> {data.fecha} {data.hora||''}<br/><b>Modalidad:</b> {data.modalidad}</div>{[['Orden del día',data.ordenDia],['Desarrollo de la reunión',data.desarrollo],['Acuerdos, responsables y fechas',data.acuerdos],['Observaciones',data.observaciones]].filter(([,v])=>v).map(([k,v])=><section key={k} style={{marginTop:18}}><b style={{color:green,fontSize:13}}>{k}</b><div style={{whiteSpace:'pre-wrap',fontSize:13,lineHeight:1.55,marginTop:5,padding:12,background:'#f8faf6',borderRadius:8}}>{v}</div></section>)}<div style={{marginTop:20,padding:12,border:`1px solid ${border}`,borderRadius:8,fontSize:12,lineHeight:1.5}}>{data.declaracion}</div>{data.estado==='Conforme'?<div style={{marginTop:18,padding:13,background:'#edf7ea',borderRadius:8,color:green,fontWeight:800}}>Conformidad registrada el {new Date(data.conformidadEn).toLocaleString('es-MX')}.</div>:<><label style={{display:'flex',gap:8,alignItems:'flex-start',marginTop:18,fontSize:13}}><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/><span>He leído el documento y manifiesto mi conformidad con su contenido y con los acuerdos asentados.</span></label><button disabled={!checked} onClick={aceptar} style={{marginTop:14,border:0,borderRadius:8,padding:'10px 15px',fontWeight:800,cursor:checked?'pointer':'not-allowed',background:checked?'#3dad2d':'#cfd6cc',color:'#fff'}}>Registrar mi conformidad</button></>}{msg&&<div style={{marginTop:12,fontSize:12,fontWeight:800,color:green}}>{msg}</div>}<p style={{marginTop:22,fontSize:10,color:muted}}>Este registro acredita una manifestación de conformidad electrónica y su fecha/hora dentro de NODO. No se presenta como firma electrónica avanzada.</p></div></main>;
}
