import React,{useEffect,useMemo,useState} from "react";
import PublicForms from "./PublicForms";

const card={background:"#fff",border:"1px solid #e6e8df",borderRadius:14,padding:18,boxShadow:"0 4px 18px rgba(37,68,45,.06)"};
const open=(u)=>u&&window.open(u,"_blank","noopener,noreferrer");
function Embed({src,title}){if(!src)return null;return <div style={{marginTop:12,border:"1px solid #dde3d9",borderRadius:10,overflow:"hidden",background:"#fff"}}><iframe title={title||"Contenido embebido"} src={src} style={{width:"100%",height:560,border:0,display:"block"}} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></div>}

function driveFileId(value=''){
  const s=String(value||'').trim();
  if(!s) return '';
  const patterns=[/\/file\/d\/([a-zA-Z0-9_-]+)/,/[/&?]id=([a-zA-Z0-9_-]+)/,/\/d\/([a-zA-Z0-9_-]+)/];
  for(const re of patterns){const m=s.match(re);if(m?.[1])return m[1];}
  return '';
}
function imageSrc(value='', fileId=''){
  const id=fileId||driveFileId(value);
  if(id)return `https://drive.google.com/thumbnail?id=${encodeURIComponent(id)}&sz=w1600`;
  return String(value||'').trim();
}
function Destacado({item,label}){return <div style={{...card,padding:0,overflow:"hidden",minHeight:260,display:"flex",flexDirection:"column"}}>{item&&(item.imagenUrl||item.url||item.driveFileId)?<img src={imageSrc(item.imagenUrl||item.url,item.driveFileId)} alt={item.titulo||label} style={{width:"100%",height:300,objectFit:"cover",background:"#eef3ea"}}/>:<div style={{height:220,display:"grid",placeItems:"center",background:"linear-gradient(135deg,#eef6e8,#fff7e9)",color:"#607064",fontWeight:800}}>{label}</div>}<div style={{padding:16}}><div style={{fontSize:11,fontWeight:900,letterSpacing:1,color:label==='AVISO'?'#ef8b00':'#3dad2d'}}>{label}</div><h3 style={{margin:"5px 0 7px",color:"#31533a"}}>{item?.titulo||`Espacio para ${label.toLowerCase()}`}</h3>{item?.descripcion&&<p style={{fontSize:13,color:"#647166",lineHeight:1.5}}>{item.descripcion}</p>}{item&&(item.url||item.embedUrl)&&<button onClick={()=>open(item.url||item.embedUrl)} style={{border:0,background:"#31533a",color:"#fff",padding:"8px 12px",borderRadius:8,fontWeight:800,cursor:"pointer"}}>Consultar</button>}</div></div>}
export default function PublicPortal(){
  const [live,setLive]=useState([]);
  const [adminOpen,setAdminOpen]=useState(false),[adminPass,setAdminPass]=useState(''),[showAdminPass,setShowAdminPass]=useState(false),[adminMsg,setAdminMsg]=useState('');
  useEffect(()=>{let alive=true;(async()=>{try{const [{db},{collection,getDocs,query,where}]=await Promise.all([import('./firebase.js'),import('firebase/firestore')]);const snap=await getDocs(query(collection(db,'publicaciones'),where('publico','==',true),where('estado','==','Publicado')));const rows=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(b.fechaPublicacion||b.actualizadoEn||'').localeCompare(String(a.fechaPublicacion||a.actualizadoEn||'')));if(alive)setLive(rows);}catch(e){console.warn('Publicaciones dinámicas no disponibles; se conserva el contenido estático.',e);}})();return()=>{alive=false};},[]);
  const flyer=useMemo(()=>live.find(x=>x.destacadoTipo==='Flyer'),[live]);
  const aviso=useMemo(()=>live.find(x=>x.destacadoTipo==='Aviso'),[live]);
  const programasPlan=useMemo(()=>live.filter(x=>x.seccionPublica==='programas'&&x.tipoContenido==='Programa Plan de Prima'),[live]);
  const generales=useMemo(()=>live.filter(x=>!x.destacadoTipo&&x.seccionPublica!=='programas'),[live]);
  const go=id=>document.getElementById(id)?.scrollIntoView({behavior:"smooth"});
  async function adminDirect(){
    setAdminMsg('');
    if(!adminPass){setAdminMsg('Ingresa tu clave de administrador.');return;}
    try{const [{auth},{signInWithEmailAndPassword}]=await Promise.all([import('./firebase.js'),import('firebase/auth')]);const email=import.meta.env.VITE_ADMIN_EMAIL||'rvalenzuela@fundacionborquezschwarzbeck.org';await signInWithEmailAndPassword(auth,email,adminPass);window.location.href='/?internal=1';}catch(e){console.error(e);setAdminMsg('Clave no válida o acceso no disponible.');}
  }
  return <div style={{fontFamily:"Inter,Arial,sans-serif",background:"#f7f8f3",color:"#263329",minHeight:"100vh"}}>
    <header style={{position:"sticky",top:0,zIndex:20,background:"rgba(255,255,255,.96)",borderBottom:"1px solid #e4e7df"}}><div style={{maxWidth:1180,margin:"0 auto",padding:"10px 20px",display:"flex",alignItems:"center",justifyContent:"space-between",gap:16}}><div style={{display:"flex",alignItems:"center",gap:12}}><img src="/logo-asociacion-comercio-justo.png" alt="Asociación de Comercio Justo Campos Bórquez A.C." style={{height:62,width:62,objectFit:"contain"}}/><div><div style={{fontWeight:800,fontSize:16}}>Asociación de Comercio Justo</div><div style={{fontSize:12,color:"#5f6d61"}}>Campos Bórquez A.C.</div></div></div><nav style={{display:"flex",gap:7,flexWrap:"wrap",justifyContent:"flex-end"}}>{[["inicio","Inicio"],["prima","Prima Fairtrade"],["programas","Programas"],["convocatorias","Convocatorias"],["resultados","Resultados"],["documentos","Documentos"]].map(([id,l])=><button key={id} onClick={()=>go(id)} style={{border:0,background:"transparent",padding:"8px 9px",cursor:"pointer",fontWeight:700,color:"#31533a"}}>{l}</button>)}</nav></div></header>
    <section id="inicio" style={{background:"linear-gradient(135deg,#f8fbf5 0%,#eef7e7 55%,#fff7e9 100%)",borderBottom:"1px solid #e4e7df"}}><div style={{maxWidth:1180,margin:"0 auto",padding:"52px 22px",display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:38,alignItems:"center"}}><div style={{textAlign:"center"}}><img src="/logo-asociacion-comercio-justo.png" alt="" style={{maxWidth:330,width:"90%",height:"auto"}}/></div><div><div style={{fontSize:12,fontWeight:800,letterSpacing:2,color:"#ef8b00",textTransform:"uppercase"}}>Portal de participantes de la prima</div><h1 style={{fontSize:"clamp(30px,4.5vw,55px)",lineHeight:1.02,margin:"8px 0 16px",color:"#264d2e"}}>Información, participación y rendición de cuentas en un mismo lugar.</h1><p style={{fontSize:17,lineHeight:1.65,color:"#536256",maxWidth:700}}>Portal de la Asociación de Comercio Justo Campos Bórquez A.C. para participantes de la Prima Fairtrade.</p><div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:20}}><button onClick={()=>go("convocatorias")} style={{border:0,background:"#3dad2d",color:"#fff",padding:"12px 18px",borderRadius:10,fontWeight:800,cursor:"pointer"}}>Ver convocatorias</button><button onClick={()=>go("resultados")} style={{border:"1px solid #3dad2d",background:"#fff",color:"#2c6c28",padding:"12px 18px",borderRadius:10,fontWeight:800,cursor:"pointer"}}>Consultar resultados</button><button onClick={()=>{window.location.href="/?firmas=1"}} style={{border:"1px solid #31533a",background:"#31533a",color:"#fff",padding:"12px 18px",borderRadius:10,fontWeight:800,cursor:"pointer"}}>Portal de Firmas</button></div></div></div></section>
    <main style={{maxWidth:1180,margin:"0 auto",padding:"34px 22px 55px"}}>
      <section id="destacados" style={{marginBottom:36}}><div style={{fontSize:12,fontWeight:900,color:"#31533a",letterSpacing:1}}>DESTACADOS</div><h2 style={{fontSize:28,margin:"5px 0 14px"}}>Convocatorias y avisos</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:14}}><Destacado item={flyer} label="FLYER / CONVOCATORIA"/><Destacado item={aviso} label="AVISO"/></div></section>
      <section id="prima" style={{marginBottom:36}}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:14}}><div style={card}><b>VENTAS Y PRIMA</b><h3>De las ventas al beneficio</h3><p>Volumen vendido, Prima Fairtrade generada y evolución por periodo.</p></div><div style={card}><b>PLAN ANUAL</b><h3>Plan de Prima 2026</h3><p>Consulta el Plan de Prima vigente del ejercicio 2026.</p><button onClick={()=>open("/documentos/plan-de-prima-2026.xlsx")} style={{border:0,background:"#31533a",color:"white",padding:"9px 12px",borderRadius:8,cursor:"pointer",fontWeight:700}}>Consultar Plan de Prima 2026</button></div><div style={card}><b>PARTICIPACIÓN</b><h3>Convocatorias</h3><p>Programas y oportunidades dirigidas a participantes vigentes.</p></div></div></section>
      <section id="programas" style={{margin:"42px 0"}}><div style={{fontSize:12,fontWeight:800,color:"#3dad2d",letterSpacing:1}}>PROGRAMAS</div><h2 style={{fontSize:30,margin:"5px 0 7px"}}>Programas y beneficios</h2>{programasPlan.length?<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:12,marginTop:16}}>{programasPlan.map(x=>{const d=x.datosPublicos||{};return <div key={x.id} style={card}><div style={{fontSize:11,fontWeight:900,color:"#3dad2d"}}>PLAN DE PRIMA {x.anio||""}</div><h3 style={{fontSize:18,lineHeight:1.25,margin:"6px 0 9px"}}>{d.proyecto||x.titulo}</h3>{d.descripcion&&<p style={{fontSize:13,lineHeight:1.5,color:"#5f6d61"}}>{d.descripcion}</p>}{d.resultadosEsperados&&<div style={{fontSize:12,marginTop:8}}><b>Resultados esperados:</b> {d.resultadosEsperados}</div>}{d.actividadesMedidas&&<div style={{fontSize:12,marginTop:8}}><b>Actividades y medidas:</b> {d.actividadesMedidas}</div>}{d.responsable&&<div style={{fontSize:12,marginTop:8}}><b>Responsable:</b> {d.responsable}</div>}{d.presupuesto!==undefined&&d.presupuesto!==''&&<div style={{fontSize:12,marginTop:8}}><b>Presupuesto:</b> {Number(d.presupuesto||0).toLocaleString("es-MX",{style:"currency",currency:"MXN"})}</div>}{d.plazo&&<div style={{fontSize:12,marginTop:8}}><b>Plazo:</b> {d.plazo}</div>}{Array.isArray(d.indicadores)&&d.indicadores.length>0&&<details style={{marginTop:10}}><summary style={{cursor:"pointer",fontWeight:800,color:"#31533a"}}>Indicadores de medición</summary><ul style={{paddingLeft:18,fontSize:12}}>{d.indicadores.map((i,n)=><li key={n}>{i.nombre}{i.meta?` — Meta: ${i.meta}`:""}</li>)}</ul></details>}</div>})}</div>:<div style={{...card,marginTop:16,color:"#5f6d61"}}>Los proyectos del Plan de Prima que se autoricen para publicación aparecerán aquí automáticamente.</div>}</section>
      <section id="convocatorias" style={{margin:"42px 0"}}><div style={{fontSize:12,fontWeight:800,color:"#cf1728",letterSpacing:1}}>CONVOCATORIAS</div><h2 style={{fontSize:30,margin:"5px 0 7px"}}>Oportunidades abiertas</h2><div style={card}>Las convocatorias y formularios que se activen desde la Mesa de trabajo aparecerán aquí automáticamente.</div><div style={{marginTop:14}}><PublicForms/></div></section>
      <section id="resultados" style={{margin:"42px 0"}}><div style={{fontSize:12,fontWeight:800,color:"#08a2dc",letterSpacing:1}}>RENDICIÓN DE CUENTAS</div><h2 style={{fontSize:30,margin:"5px 0 7px"}}>Resultados para participantes</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12,marginTop:16}}>{["Volumen vendido","Prima generada","Participantes vigentes","Beneficiarios","Actividades","Valor de beneficios"].map(a=><div key={a} style={card}><b>{a}</b></div>)}</div></section>
      {generales.length>0&&<section id="publicaciones" style={{margin:"42px 0"}}><div style={{fontSize:12,fontWeight:800,color:"#3dad2d",letterSpacing:1}}>PUBLICADO DESDE LA MESA DE TRABAJO</div><h2 style={{fontSize:30,margin:"5px 0 7px"}}>Actualizaciones de la Asociación</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(250px,1fr))",gap:12,marginTop:16}}>{generales.map(x=><div key={x.id} style={card}><div style={{fontSize:11,fontWeight:800,color:"#3dad2d",textTransform:"uppercase"}}>{x.categoria||"Publicación"}</div>{x.tipoContenido==='Imagen'&&(x.imagenUrl||x.url||x.driveFileId)&&<img src={imageSrc(x.imagenUrl||x.url,x.driveFileId)} alt={x.titulo} style={{width:"100%",maxHeight:260,objectFit:"cover",borderRadius:9,marginTop:8}}/>}<h3 style={{margin:"8px 0 6px"}}>{x.titulo}</h3>{x.descripcion&&<p style={{fontSize:13,lineHeight:1.5,color:"#5f6d61"}}>{x.descripcion}</p>}{x.tipoContenido==='Formulario embebido'&&x.embedUrl?<Embed src={x.embedUrl} title={x.titulo}/>:x.url&&<button onClick={()=>open(x.url)} style={{border:0,background:"#31533a",color:"white",padding:"8px 12px",borderRadius:8,cursor:"pointer",fontWeight:700}}>Consultar</button>}</div>)}</div></section>}
      <section id="documentos" style={{margin:"42px 0"}}><div style={{fontSize:12,fontWeight:800,color:"#ef8b00",letterSpacing:1}}>DOCUMENTOS PÚBLICOS</div><h2 style={{fontSize:30,margin:"5px 0 7px"}}>Información institucional</h2><div style={{display:"grid",gap:10}}>{[["Plan de Prima 2026","/documentos/plan-de-prima-2026.xlsx"],["Constitución de la Asociación","/documentos/constitucion-acjcb.pdf"],["Lineamientos de Emergencias Médicas","/documentos/lineamientos-emergencias-medicas.pdf"],["Lineamientos de Rehabilitación de Vivienda","/documentos/lineamientos-rehabilitacion-vivienda.pdf"],["Reglas de Operación de Becas Escolares","/documentos/reglas-operacion-becas-escolares-2026.pdf"]].map(([n,u])=><div key={n} style={{...card,display:"flex",justifyContent:"space-between",alignItems:"center",gap:12}}><b>{n}</b><button onClick={()=>open(u)} style={{border:0,background:"#31533a",color:"white",padding:"8px 12px",borderRadius:8,cursor:"pointer",fontWeight:700}}>Consultar</button></div>)}</div></section>
    </main><footer style={{borderTop:"1px solid #e0e4db",background:"#fff",padding:"20px",textAlign:"center",fontSize:12,color:"#6e786f"}}>Asociación de Comercio Justo Campos Bórquez A.C.</footer>
    <button aria-label="Acceso administrador" onClick={()=>setAdminOpen(true)} style={{position:"fixed",right:16,bottom:16,width:42,height:42,borderRadius:21,border:"1px solid #dfe5dc",background:"#fff",color:"#31533a",fontSize:24,fontWeight:900,cursor:"pointer",boxShadow:"0 5px 18px rgba(0,0,0,.12)"}}>⋯</button>
    {adminOpen&&<div style={{position:"fixed",inset:0,zIndex:100,background:"rgba(20,35,24,.42)",display:"grid",placeItems:"center",padding:20}}><div style={{width:"min(380px,100%)",background:"#fff",borderRadius:14,padding:20,boxShadow:"0 20px 55px rgba(0,0,0,.25)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><h3 style={{margin:0,color:"#31533a"}}>Acceso administrador</h3><button onClick={()=>setAdminOpen(false)} style={{border:0,background:"transparent",fontSize:20,cursor:"pointer"}}>×</button></div><p style={{fontSize:12,color:"#667268"}}>Ingresa únicamente tu clave. El correo de administración se utiliza internamente.</p><div style={{position:"relative"}}><input type={showAdminPass?"text":"password"} autoFocus value={adminPass} onChange={e=>setAdminPass(e.target.value)} onKeyDown={e=>e.key==='Enter'&&adminDirect()} style={{width:"100%",boxSizing:"border-box",padding:"10px 88px 10px 12px",border:"1px solid #dfe5dc",borderRadius:9}}/><button type="button" onClick={()=>setShowAdminPass(v=>!v)} style={{position:"absolute",right:7,top:"50%",transform:"translateY(-50%)",border:0,background:"transparent",color:"#31533a",fontWeight:800,cursor:"pointer"}}>{showAdminPass?"Ocultar":"Mostrar"}</button></div><button onClick={adminDirect} style={{width:"100%",marginTop:10,border:0,background:"#31533a",color:"#fff",padding:"10px",borderRadius:9,fontWeight:800,cursor:"pointer"}}>Entrar</button>{adminMsg&&<div style={{marginTop:9,fontSize:12,color:"#a12626",fontWeight:700}}>{adminMsg}</div>}</div></div>}
  </div>;
}
