import React,{useEffect,useMemo,useState} from 'react';
import {collection,doc,getDocs,query,setDoc,where} from 'firebase/firestore';
import {db} from './firebase';
import {uploadToNodoDrive} from './config/driveUpload';
const green='#31533a',bright='#3dad2d',border='#dfe5dc',muted='#667268';
const input={width:'100%',boxSizing:'border-box',padding:'10px 12px',border:`1px solid ${border}`,borderRadius:9,background:'#fff'};
const uid=()=>`${Date.now().toString(36)}${Math.random().toString(36).slice(2,8)}`;
function renderField(f,value,setValue){const common={style:input,value:value??'',onChange:e=>setValue(e.target.type==='checkbox'?e.target.checked:e.target.value),required:!!f.obligatorio};if(f.tipo==='Texto largo')return <textarea {...common} style={{...input,minHeight:90}}/>;if(f.tipo==='Selección')return <select {...common}><option value="">Selecciona</option>{String(f.opciones||'').split(',').map(x=>x.trim()).filter(Boolean).map(x=><option key={x}>{x}</option>)}</select>;if(f.tipo==='Sí/No')return <select {...common}><option value="">Selecciona</option><option value="Sí">Sí</option><option value="No">No</option></select>;if(f.tipo==='Archivo')return <input style={input} type="file" required={!!f.obligatorio} onChange={e=>setValue(e.target.files?.[0]||null)}/>;const types={Número:'number',Correo:'email',Teléfono:'tel',Fecha:'date',URL:'url'};return <input {...common} type={types[f.tipo]||'text'}/>}
async function uploadFile(file,context){if(!file)return null;return await uploadToNodoDrive(file,{folderKey:'solicitudes',context});}
export default function PublicForms(){
 const [artefactos,setArtefactos]=useState([]),[programas,setProgramas]=useState([]),[actividades,setActividades]=useState([]),[selected,setSelected]=useState(null),[values,setValues]=useState({}),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{(async()=>{try{const [ar,pr,ac]=await Promise.all([getDocs(query(collection(db,'artefactos'),where('publico','==',true),where('estado','==','Publicado'))),getDocs(collection(db,'programas')),getDocs(collection(db,'actividades'))]);setArtefactos(ar.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.tipo==='Formulario'));setProgramas(pr.docs.map(d=>({id:d.id,...d.data()})));setActividades(ac.docs.map(d=>({id:d.id,...d.data()})));}catch(e){console.warn(e)}})()},[]);
 const fields=useMemo(()=>[...(selected?.campos||[])].sort((a,b)=>(a.orden||0)-(b.orden||0)),[selected]);
 async function submit(){if(!selected)return;for(const f of fields){if(f.obligatorio&&!values[f.id]){setMsg(`Falta completar: ${f.etiqueta}`);return;}}setBusy(true);setMsg('');try{const solicitudId=`sol-${uid()}`,codigo=`${Math.random().toString(36).slice(2,6)}-${Math.random().toString(36).slice(2,6)}`.toUpperCase(),respuestas={};for(const f of fields){const v=values[f.id];if(f.tipo==='Archivo'&&v instanceof File){const up=await uploadFile(v,{solicitudId,programaId:selected.programaId,actividadId:selected.actividadId,artefactoId:selected.id,campoId:f.id});respuestas[f.id]={etiqueta:f.etiqueta,tipo:f.tipo,valor:up?.url||'',driveFileId:up?.fileId||'',archivoNombre:v.name};}else respuestas[f.id]={etiqueta:f.etiqueta,tipo:f.tipo,valor:v??''};}
 const now=new Date().toISOString();const payload={solicitudId,codigoAcceso:codigo,programaId:selected.programaId,actividadId:selected.actividadId,artefactoId:selected.id,formularioId:selected.id,formularioNombre:selected.nombre,estatus:'Solicitud recibida',respuestas,trazabilidad:{programaId:selected.programaId,actividadId:selected.actividadId,artefactoId:selected.id,solicitudId},creadoEn:now,actualizadoEn:now,origen:'Portal público'};await setDoc(doc(db,'solicitudes',solicitudId),payload);setMsg(`Solicitud recibida. Código de seguimiento: ${codigo}`);setValues({});}catch(e){console.error(e);setMsg(e.message||'No fue posible enviar la solicitud.');}finally{setBusy(false)}}
 if(artefactos.length===0)return <div style={{padding:16,border:`1px dashed ${border}`,borderRadius:10,color:muted}}>No hay formularios públicos activos en este momento.</div>;
 return <div style={{display:'grid',gap:12}}>{!selected?<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:10}}>{artefactos.map(x=>{const p=programas.find(p=>p.id===x.programaId),a=actividades.find(a=>a.id===x.actividadId);return <div key={x.id} style={{background:'#fff',border:`1px solid ${border}`,borderRadius:12,padding:16}}><div style={{fontSize:11,fontWeight:900,color:bright}}>FORMULARIO</div><h3 style={{margin:'5px 0'}}>{x.nombre}</h3><div style={{fontSize:12,color:muted}}>{p?.nombre}{a&&` · ${a.nombre}`}</div>{x.descripcion&&<p style={{fontSize:13,lineHeight:1.5}}>{x.descripcion}</p>}<button onClick={()=>{setSelected(x);setValues({});setMsg('')}} style={{border:0,background:green,color:'#fff',padding:'9px 12px',borderRadius:8,fontWeight:800,cursor:'pointer'}}>Abrir formulario</button></div>})}</div>:<div style={{background:'#fff',border:`1px solid ${border}`,borderRadius:14,padding:18}}><button onClick={()=>setSelected(null)} style={{border:0,background:'transparent',color:green,fontWeight:800,cursor:'pointer'}}>← Volver</button><h3>{selected.nombre}</h3>{selected.descripcion&&<p style={{color:muted}}>{selected.descripcion}</p>}<div style={{display:'grid',gap:11}}>{fields.map(f=><div key={f.id}><label style={{display:'block',fontSize:12,fontWeight:800,marginBottom:4}}>{f.etiqueta}{f.obligatorio?' *':''}</label>{renderField(f,values[f.id],v=>setValues(s=>({...s,[f.id]:v})))}{f.ayuda&&<div style={{fontSize:11,color:muted}}>{f.ayuda}</div>}</div>)}</div><button disabled={busy} onClick={submit} style={{border:0,background:bright,color:'#fff',padding:'11px 15px',borderRadius:9,fontWeight:900,cursor:'pointer',marginTop:14}}>{busy?'Enviando…':'Enviar solicitud'}</button>{msg&&<div style={{marginTop:12,padding:10,borderRadius:8,background:'#f2f7ee',fontWeight:800,color:green}}>{msg}</div>}</div>}</div>;
}
